version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=image_gallery
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - MYSQL_DATABASE=image_gallery
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

volumes:
  mysql_data: